<?php
/**
 * Created by JetBrains PhpStorm.
 * User: evgenius
 * Date: 9/16/13
 * Time: 11:48 PM
 * To change this template use File | Settings | File Templates.
 */

$steps = array(
    array(
        "CurrentStepID" => "welcome",
        "NextStepID" => "agreement",
        "StepNext" => "Далее"
    ),
    array(
        "CurrentStepID"         => "agreement",
        "PreviousStepID"        => "welcome",
        "NextStepID"            => "select_database",
        "__wiz_agree_license"   => "Y",
        "StepNext"              => "Далее"
    ),
    array(
        "CurrentStepID"         => "select_database",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "PreviousStepID"        => "agreement",
        "PHPSESSID"             => "#cookies.PHPSESSID#",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "StepNext"              => "Далее"
    ),
    array(
        "CurrentStepID"         => "requirements",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "_wiz_user_name"        => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-XHWQPN5A0WO4COFW",
        "PreviousStepID"        => "select_database",
        "NextStepID"            => "create_database",
        "PHPSESSID"             => "#cookies.PHPSESSID#",
        "StepNext"              => "Далее"
    ),

    array(
        "CurrentStepID"         => "create_database",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-SPT6NXHX2U4DTOZV",
        "PreviousStepID"        => "requirements",
        "NextStepID"            => "create_modules",
        "PHPSESSID"             => "#cookies.PHPSESSID#",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms" => "0600",
        "__wiz_folder_access_perms" => "0700",
        "StepNext"              => "Далее"
    ),








    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "main",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "main",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "main",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "bitrix.sitecorporate",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "bitrix.sitecorporate",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "bitrix.sitecorporate",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "bitrixcloud",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "bitrixcloud",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "bitrixcloud",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "clouds",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "clouds",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "clouds",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "compression",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "compression",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "compression",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "fileman",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "fileman",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "fileman",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "iblock",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "iblock",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "iblock",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "perfmon",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "perfmon",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "perfmon",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "search",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "search",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "search",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "seo",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "seo",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "seo",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "socialservices",
        "__wiz_nextStepStage"       => "utf8"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "socialservices",
        "__wiz_nextStepStage"       => "database"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "socialservices",
        "__wiz_nextStepStage"       => "files"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "remove_mysql",
        "__wiz_nextStepStage"       => "single"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "remove_mssql",
        "__wiz_nextStepStage"       => "single"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "remove_oracle",
        "__wiz_nextStepStage"       => "single"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "remove_misc",
        "__wiz_nextStepStage"       => "single"

    ),
    array(
        "CurrentStepID"         => "create_modules",
        "__wiz_agree_license"   => "Y",
        "__wiz_dbType"          => "mysql",
        "__wiz_lic_key_variant" => "Y",
        "__wiz_user_name"       => "qwe",
        "__wiz_user_surname"    => "qwe",
        "__wiz_email"           => "qwe@qwe.qw",
        "__wiz_utf8"            => "Y",
        "__wiz_license"         => "S12-ML-M1MNNAOWM9TNIUFK",
        "__wiz_host"            => "localhost",
        "__wiz_create_user"     => "N",
        "__wiz_user"            => "root",
        "__wiz_password"        => "qwerty",
        "__wiz_create_database" => "Y",
        "__wiz_database"        => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"       => "root",
        "__wiz_root_password"   => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "__finish",
        "__wiz_nextStepStage"       => "single"

    ),








    array(
        "CurrentStepID"             => "create_admin",
        "__wiz_agree_license"       => "Y",
        "__wiz_dbType"              => "mysql",
        "__wiz_lic_key_variant"     => "Y",
        "__wiz_utf8"                => "Y",
        "__wiz_license"             => "S12-ML-M6CXWR60P4XCIZN3",
        "__wiz_host"                => "localhost",
        "__wiz_create_user"         => "N",
        "__wiz_user"                => "root",
        "__wiz_password"            => "qwerty",
        "__wiz_create_database"     => "Y",
        "__wiz_database"            => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"           => "root",
        "__wiz_root_password"       => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "__finish",
        "__wiz_nextStepStage"       => "single",
        "NextStepID"                => "select_wizard",
        "__wiz_login"               => "admin",
        "__wiz_admin_password"      => "qwerty",
        "__wiz_admin_password_confirm" => "qwerty",
        "__wiz_email"               => "qwe@qwe.qw",
        "__wiz_user_name"           => "qwe",
        "__wiz_user_surname"        => "qwe",
        "StepNext"                  => "Далее"
    ),

    array(
        "CurrentStepID"             => "select_wizard",
        "__wiz_agree_license"       => "Y",
        "__wiz_dbType"              => "mysql",
        "__wiz_lic_key_variant"     => "Y",
        "__wiz_utf8"                => "Y",
        "__wiz_license"             => "S12-ML-4PUYB26Z2GLWRK3Z",
        "__wiz_host"                => "localhost",
        "__wiz_create_user"         => "N",
        "__wiz_user"                => "root",
        "__wiz_password"            => "qwerty",
        "__wiz_create_database"     => "Y",
        "__wiz_database"            => "new_database",
        "__wiz_create_database_type" => "",
        "__wiz_root_user"           => "root",
        "__wiz_root_password"       => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "__finish",
        "__wiz_nextStepStage"       => "single",
        "__wiz_login"               => "admin",
        "__wiz_admin_password"      => "qwerty",
        "__wiz_admin_password_confirm" => "qwerty",
        "__wiz_email"               => "qwe@qwe.qwe",
        "__wiz_user_name"           => "qwe",
        "__wiz_user_surname"        => "qwe",
        "NextStepID"                => "finish",
        "redio"                     => "on",
        "__wiz_selected_wizard"     => "@",
        "StepNext"                  => "Далее"
    ),
    array(
        "CurrentStepID"             => "load_module",
        "__wiz_agree_license"       => "Y",
        "__wiz_dbType"              => "mysql",
        "__wiz_lic_key_variant"     => "Y",
        "__wiz_utf8"                => "Y",
        "__wiz_license"             => "S12-ML-T6839AVOLBOUD9OH",
        "__wiz_host"                => "localhost",
        "__wiz_create_user"         => "N",
        "__wiz_user"                => "root",
        "__wiz_password"            => "qwerty",
        "__wiz_create_database"     => "Y",
        "__wiz_database"            => "new_database",
        "__wiz_create_database_type"    => "",
        "__wiz_root_user"           => "root",
        "__wiz_root_password"       => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_nextStep"            => "__finish",
        "__wiz_nextStepStage"       => "single",
        "__wiz_login"               => "admin",
        "__wiz_admin_password"      => "qwerty",
        "__wiz_admin_password_confirm"  => "qwerty",
        "__wiz_email"               => "qwe@qwe.qw",
        "__wiz_user_name"           => "qwe",
        "__wiz_user_surname"        => "qwe",
        "__wiz_selected_wizard"     => "@",
        "NextStepID"                => "select_wizard1",
        "redio"                     => "on",
        "__wiz_selected_module"     => "nsandrey.emptyinstall",
        "StepNext"                  => "Далее"
    ),





    array(
        "CurrentStepID"             => "load_module_action",
        "__wiz_agree_license"       => "Y",
        "__wiz_dbType"              => "mysql",
        "__wiz_lic_key_variant"     => "Y",
        "__wiz_utf8"                => "Y",
        "__wiz_license"             => "S12-ML-50BUEIVZIXCY7SO8",
        "__wiz_host"                => "localhost",
        "__wiz_create_user"         => "N",
        "__wiz_user"                => "root",
        "__wiz_password"            => "qwerty",
        "__wiz_create_database"     => "Y",
        "__wiz_database"            => "new_database",
        "__wiz_create_database_type"    => "",
        "__wiz_root_user"           => "root",
        "__wiz_root_password"       => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_login"               => "admin",
        "__wiz_admin_password"      => "qwerty",
        "__wiz_admin_password_confirm" => "qwerty",
        "__wiz_email"               => "qwe@qwe.qw",
        "__wiz_user_name"           => "qwe",
        "__wiz_user_surname"        => "qwe",
        "__wiz_selected_wizard"     => "@",
        "__wiz_selected_module"     => "nsandrey.emptyinstall",
        "__wiz_MP_ACT_OK"           => "",
        "__wiz_nextStep"            => "do_load_module",
        "__wiz_nextStepStage"       => "nsandrey.emptyinstall"
    ),
    array(
        "CurrentStepID"             => "load_module_action",
        "__wiz_agree_license"       => "Y",
        "__wiz_dbType"              => "mysql",
        "__wiz_lic_key_variant"     => "Y",
        "__wiz_utf8"                => "Y",
        "__wiz_license"             => "S12-ML-50BUEIVZIXCY7SO8",
        "__wiz_host"                => "localhost",
        "__wiz_create_user"         => "N",
        "__wiz_user"                => "root",
        "__wiz_password"            => "qwerty",
        "__wiz_create_database"     => "Y",
        "__wiz_database"            => "new_database",
        "__wiz_create_database_type"    => "",
        "__wiz_root_user"           => "root",
        "__wiz_root_password"       => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_login"               => "admin",
        "__wiz_admin_password"      => "qwerty",
        "__wiz_admin_password_confirm" => "qwerty",
        "__wiz_email"               => "qwe@qwe.qw",
        "__wiz_user_name"           => "qwe",
        "__wiz_user_surname"        => "qwe",
        "__wiz_selected_wizard"     => "@",
        "__wiz_selected_module"     => "nsandrey.emptyinstall",
        "__wiz_MP_ACT_OK"           => "",
        "__wiz_nextStep"            => "do_install_module",
        "__wiz_nextStepStage"       => "nsandrey.emptyinstall"
    ),
    array(
        "CurrentStepID"             => "load_module_action",
        "__wiz_agree_license"       => "Y",
        "__wiz_dbType"              => "mysql",
        "__wiz_lic_key_variant"     => "Y",
        "__wiz_utf8"                => "Y",
        "__wiz_license"             => "S12-ML-50BUEIVZIXCY7SO8",
        "__wiz_host"                => "localhost",
        "__wiz_create_user"         => "N",
        "__wiz_user"                => "root",
        "__wiz_password"            => "qwerty",
        "__wiz_create_database"     => "Y",
        "__wiz_database"            => "new_database",
        "__wiz_create_database_type"    => "",
        "__wiz_root_user"           => "root",
        "__wiz_root_password"       => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_login"               => "admin",
        "__wiz_admin_password"      => "qwerty",
        "__wiz_admin_password_confirm" => "qwerty",
        "__wiz_email"               => "qwe@qwe.qw",
        "__wiz_user_name"           => "qwe",
        "__wiz_user_surname"        => "qwe",
        "__wiz_selected_wizard"     => "@",
        "__wiz_selected_module"     => "nsandrey.emptyinstall",
        "__wiz_MP_ACT_OK"           => "",
        "__wiz_nextStep"            => "do_load_wizard",
        "__wiz_nextStepStage"       => "nsandrey.emptyinstall"
    ),
    array(
        "CurrentStepID"             => "load_module_action",
        "__wiz_agree_license"       => "Y",
        "__wiz_dbType"              => "mysql",
        "__wiz_lic_key_variant"     => "Y",
        "__wiz_utf8"                => "Y",
        "__wiz_license"             => "S12-ML-50BUEIVZIXCY7SO8",
        "__wiz_host"                => "localhost",
        "__wiz_create_user"         => "N",
        "__wiz_user"                => "root",
        "__wiz_password"            => "qwerty",
        "__wiz_create_database"     => "Y",
        "__wiz_database"            => "new_database",
        "__wiz_create_database_type"    => "",
        "__wiz_root_user"           => "root",
        "__wiz_root_password"       => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_login"               => "admin",
        "__wiz_admin_password"      => "qwerty",
        "__wiz_admin_password_confirm" => "qwerty",
        "__wiz_email"               => "qwe@qwe.qw",
        "__wiz_user_name"           => "qwe",
        "__wiz_user_surname"        => "qwe",
        "__wiz_selected_wizard"     => "@",
        "__wiz_selected_module"     => "nsandrey.emptyinstall",
        "__wiz_MP_ACT_OK"           => "",
        "__wiz_nextStep"            => "do_load_wizard",
        "__wiz_nextStepStage"       => "nsandrey.emptyinstall"
    ),
    array(
        "CurrentStepID"             => "load_module_action",
        "__wiz_agree_license"       => "Y",
        "__wiz_dbType"              => "mysql",
        "__wiz_lic_key_variant"     => "Y",
        "__wiz_utf8"                => "Y",
        "__wiz_license"             => "S12-ML-50BUEIVZIXCY7SO8",
        "__wiz_host"                => "localhost",
        "__wiz_create_user"         => "N",
        "__wiz_user"                => "root",
        "__wiz_password"            => "qwerty",
        "__wiz_create_database"     => "Y",
        "__wiz_database"            => "new_database",
        "__wiz_create_database_type"    => "",
        "__wiz_root_user"           => "root",
        "__wiz_root_password"       => "qwerty",
        "__wiz_file_access_perms"   => "0600",
        "__wiz_folder_access_perms" => "0700",
        "__wiz_login"               => "admin",
        "__wiz_admin_password"      => "qwerty",
        "__wiz_admin_password_confirm" => "qwerty",
        "__wiz_email"               => "qwe@qwe.qw",
        "__wiz_user_name"           => "qwe",
        "__wiz_user_surname"        => "qwe",
        "__wiz_selected_wizard"     => "@",
        "__wiz_selected_module"     => "nsandrey.emptyinstall",
        "__wiz_MP_ACT_OK"           => "",
        "__wiz_nextStep"            => "LocalRedirect",
        "__wiz_nextStepStage"       => "nsandrey.emptyinstall"
    ),


    array(
        "CurrentStepID"             => "set_template",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "StepNext"                  => "Настройка решения"
    ),
    array(
        "CurrentStepID"             => "set_template",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "StepNext"                  => "Настройка модулей"
    ),



    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "0",
        "__wiz_nextStepStage"       => "skip"
    ),
    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "1",
        "__wiz_nextStepStage"       => "skip"
    ),
    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "2",
        "__wiz_nextStepStage"       => "skip"
    ),
    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "3",
        "__wiz_nextStepStage"       => "skip"
    ),
    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "4",
        "__wiz_nextStepStage"       => "skip"
    ),
    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "5",
        "__wiz_nextStepStage"       => "skip"
    ),
    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "6",
        "__wiz_nextStepStage"       => "skip"
    ),
    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "7",
        "__wiz_nextStepStage"       => "skip"
    ),
    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "8",
        "__wiz_nextStepStage"       => "skip"
    ),
    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "9",
        "__wiz_nextStepStage"       => "skip"
    ),
    array(
        "CurrentStepID"             => "install_step",
        "__wiz_b_modules[iblock]"   => "Информационные блоки",
        "__wiz_b_modules[compression]"  => "Компрессия",
        "__wiz_b_modules[perfmon]"  => "Модуль производительности",
        "__wiz_b_modules[bitrixcloud]"  => "Облако \"1С-Битрикс\"",
        "__wiz_b_modules[clouds]"   => "Облачные хранилища",
        "__wiz_b_modules[search]"   => "Поиск",
        "__wiz_b_modules[seo]"      => "Поисковая оптимизация",
        "__wiz_b_modules[socialservices]"   => "Социальные сервисы",
        "NextStepID"                => "set_site",
        "__wiz_templateName"        => "Пустой шаблон",
        "__wiz_templateDescription" => "Пустой шаблон для сайта",
        "__wiz_templateDir"         => "empty",
        "NextStepID"                  => "set_modules",
        "__wiz_siteName"            => "Название сайта",
        "__wiz_siteMetaTitle"       => "Title",
        "__wiz_siteMetaDescription" => "Description",
        "__wiz_siteMetaKeywords"    => "Keywords",
        "__wiz_install[0]"          => "iblock",
        "__wiz_install[1]"          => "compression",
        "__wiz_install[2]"          => "perfmon",
        "__wiz_install[3]"          => "bitrixcloud",
        "__wiz_install[4]"          => "clouds",
        "__wiz_install[5]"          => "search",
        "__wiz_install[6]"          => "seo",
        "__wiz_install[7]"          => "socialservices",
        "__wiz_nextStep"            => "10",
        "__wiz_nextStepStage"       => "skip"
    )

);